import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :hiraeth, HiraethWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Force using SSL in production. This also sets the "strict-security-transport" header,
# known as HSTS. If you have a health check endpoint, you may want to exclude it below.
# Note `:force_ssl` is required to be set at compile-time.
config :hiraeth, HiraethWeb.Endpoint,
  force_ssl: [
    rewrite_on: [:x_forwarded_proto],
    exclude: [
      paths: ["/health"],
      hosts: ["localhost", "127.0.0.1"]
    ]
  ]

# Readiness: the /ready probe must require the private sidecar to be healthy
# before the app reports ready in production.
config :hiraeth, :readiness, require_sidecar: true

# Session cookie hardening: mark the cookie Secure (HTTPS-only) in prod and
# gate the LiveDashboard RequestLogger debugging plug out of prod.
config :hiraeth, :session_cookie_secure, true
config :hiraeth, :disable_request_logger, true

# Do not print debug messages in production
config :logger, level: :info

# JSON logs in prod; :default_handler formatter overrides the legacy :default_formatter (dev/test keep text).
config :logger, :default_handler,
  formatter: {LoggerJSON.Formatters.Basic, metadata: [:request_id]}

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
