defmodule Hiraeth.Repo.Migrations.CoversLifecycle do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:cover_assets) do
      add :cached_file_path, :text
      add :cached_at, :utc_datetime
    end
  end

  def down do
    alter table(:cover_assets) do
      remove :cached_at
      remove :cached_file_path
    end
  end
end
