defmodule Hiraeth.Repo.Migrations.InitialResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:works, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text, null: false
      add :subtitle, :text
      add :slug, :text, null: false
      add :publication_state, :text, null: false, default: "draft"
    end

    create unique_index(:works, [:slug], name: "works_unique_slug_index")

    create table(:users, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :email, :citext, null: false
      add :display_name, :text
      add :admin?, :boolean, null: false, default: false
    end

    create unique_index(:users, [:email], name: "users_unique_email_index")

    create table(:tokens, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :purpose, :text, null: false
      add :token_hash, :text, null: false
      add :expires_at, :utc_datetime

      add :user_id,
          references(:users,
            column: :id,
            name: "tokens_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:tokens, [:token_hash], name: "tokens_unique_token_hash_index")

    create table(:staged_import_rows, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :row_number, :bigint, null: false
      add :raw_payload, :map
      add :status, :text, null: false, default: "pending"
      add :import_run_id, :uuid, null: false
    end

    create unique_index(:staged_import_rows, [:import_run_id, :row_number],
             name: "staged_import_rows_unique_import_row_index"
           )

    create table(:source_records, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :provider, :text, null: false
      add :source_type, :text, null: false
      add :source_uri, :text
      add :file_checksum, :text
      add :license_note, :text
      add :raw_payload, :map
      add :imported_at, :utc_datetime
    end

    create unique_index(:source_records, [:provider, :source_type, :source_uri, :file_checksum],
             name: "source_records_unique_source_record_index"
           )

    create table(:source_ledger_entries, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :event_type, :text, null: false
      add :message, :text
      add :occurred_at, :utc_datetime

      add :source_record_id,
          references(:source_records,
            column: :id,
            name: "source_ledger_entries_source_record_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:source_ledger_entries, [:source_record_id, :event_type, :occurred_at],
             name: "source_ledger_entries_unique_source_event_index"
           )

    create table(:series_memberships, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :position, :bigint
      add :label, :text
      add :series_id, :uuid, null: false
      add :work_id, :uuid, null: false
    end

    create unique_index(:series_memberships, [:series_id, :work_id],
             name: "series_memberships_unique_series_work_index"
           )

    create table(:series, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:series_memberships) do
      modify :series_id,
             references(:series,
               column: :id,
               name: "series_memberships_series_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :work_id,
             references(:works,
               column: :id,
               name: "series_memberships_work_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:series) do
      add :title, :text, null: false
      add :slug, :text, null: false
      add :publisher_id, :uuid
    end

    create unique_index(:series, [:slug], name: "series_unique_slug_index")

    create table(:review_items, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :entity_type, :text, null: false
      add :decision, :text, null: false, default: "pending"
      add :message, :text
      add :import_run_id, :uuid, null: false
      add :staged_import_row_id, :uuid
    end

    create unique_index(:review_items, [:import_run_id, :entity_type, :id],
             name: "review_items_unique_review_item_index"
           )

    create table(:publishers, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:series) do
      modify :publisher_id,
             references(:publishers,
               column: :id,
               name: "series_publisher_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:publishers) do
      add :name, :text, null: false
      add :slug, :text, null: false
      add :description, :text
    end

    create unique_index(:publishers, [:slug], name: "publishers_unique_slug_index")

    create table(:imprints, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :slug, :text, null: false

      add :publisher_id,
          references(:publishers,
            column: :id,
            name: "imprints_publisher_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:imprints, [:publisher_id, :slug],
             name: "imprints_unique_publisher_slug_index"
           )

    create table(:import_runs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :provider, :text, null: false
      add :status, :text, null: false, default: "draft"
      add :row_limit, :bigint, null: false, default: 250
    end

    create unique_index(:import_runs, [:provider, :status, :id],
             name: "import_runs_unique_provider_status_index"
           )

    alter table(:staged_import_rows) do
      modify :import_run_id,
             references(:import_runs,
               column: :id,
               name: "staged_import_rows_import_run_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:review_items) do
      modify :import_run_id,
             references(:import_runs,
               column: :id,
               name: "review_items_import_run_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :staged_import_row_id,
             references(:staged_import_rows,
               column: :id,
               name: "review_items_staged_import_row_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create table(:import_mappings, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :source_column, :text, null: false
      add :target_field, :text, null: false

      add :import_run_id,
          references(:import_runs,
            column: :id,
            name: "import_mappings_import_run_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:import_mappings, [:import_run_id, :source_column, :target_field],
             name: "import_mappings_unique_import_mapping_index"
           )

    create table(:identifiers, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :identifier_type, :text, null: false
      add :value, :text, null: false
      add :edition_id, :uuid, null: false
    end

    create unique_index(:identifiers, [:identifier_type, :value],
             name: "identifiers_unique_identifier_index"
           )

    create table(:editions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:identifiers) do
      modify :edition_id,
             references(:editions,
               column: :id,
               name: "identifiers_edition_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:editions) do
      add :title, :text, null: false
      add :subtitle, :text
      add :slug, :text, null: false
      add :format, :text
      add :published_on, :date

      add :work_id,
          references(:works,
            column: :id,
            name: "editions_work_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :publisher_id,
          references(:publishers,
            column: :id,
            name: "editions_publisher_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :imprint_id,
          references(:imprints,
            column: :id,
            name: "editions_imprint_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:editions, [:slug], name: "editions_unique_slug_index")

    create table(:curation_overrides, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :entity_type, :text, null: false
      add :entity_id, :uuid, null: false
      add :field_name, :text, null: false
      add :curated_value, :text
      add :reason, :text

      add :source_record_id,
          references(:source_records,
            column: :id,
            name: "curation_overrides_source_record_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :reviewer_id,
          references(:users,
            column: :id,
            name: "curation_overrides_reviewer_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:curation_overrides, [:entity_type, :entity_id, :field_name],
             name: "curation_overrides_unique_entity_field_index"
           )

    create table(:cover_assignments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :position, :bigint
      add :visible?, :boolean, null: false, default: true
      add :cover_asset_id, :uuid, null: false
      add :edition_id, :uuid, null: false
    end

    create unique_index(:cover_assignments, [:edition_id, :cover_asset_id],
             name: "cover_assignments_unique_edition_cover_index"
           )

    create table(:cover_assets, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:cover_assignments) do
      modify :cover_asset_id,
             references(:cover_assets,
               column: :id,
               name: "cover_assignments_cover_asset_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :edition_id,
             references(:editions,
               column: :id,
               name: "cover_assignments_edition_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:cover_assets) do
      add :source_url, :text, null: false
      add :provider, :text, null: false
      add :rights_basis, :text, null: false
      add :attribution_text, :text
      add :attribution_url, :text
      add :cache_policy, :text, null: false, default: "link_only"
      add :takedown_state, :text, null: false, default: "visible"
    end

    create unique_index(:cover_assets, [:source_url],
             name: "cover_assets_unique_source_url_index"
           )

    create table(:contributors, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :display_name, :text, null: false
      add :sort_name, :text
      add :slug, :text, null: false
    end

    create unique_index(:contributors, [:slug], name: "contributors_unique_slug_index")

    create table(:contributions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :role, :text, null: false
      add :position, :bigint

      add :contributor_id,
          references(:contributors,
            column: :id,
            name: "contributions_contributor_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :work_id,
          references(:works,
            column: :id,
            name: "contributions_work_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :edition_id,
          references(:editions,
            column: :id,
            name: "contributions_edition_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:contributions, [:contributor_id, :role, :work_id, :edition_id],
             name: "contributions_unique_contribution_slot_index"
           )

    create table(:audit_events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :event_type, :text, null: false
      add :entity_type, :text
      add :entity_id, :uuid
      add :metadata, :map
      add :occurred_at, :utc_datetime

      add :actor_id,
          references(:users,
            column: :id,
            name: "audit_events_actor_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:audit_events, [:event_type, :entity_type, :entity_id, :occurred_at],
             name: "audit_events_unique_audit_event_index"
           )
  end

  def down do
    drop constraint(:audit_events, "audit_events_actor_id_fkey")

    drop_if_exists unique_index(
                     :audit_events,
                     [:event_type, :entity_type, :entity_id, :occurred_at],
                     name: "audit_events_unique_audit_event_index"
                   )

    drop table(:audit_events)

    drop constraint(:contributions, "contributions_contributor_id_fkey")

    drop constraint(:contributions, "contributions_work_id_fkey")

    drop constraint(:contributions, "contributions_edition_id_fkey")

    drop_if_exists unique_index(:contributions, [:contributor_id, :role, :work_id, :edition_id],
                     name: "contributions_unique_contribution_slot_index"
                   )

    drop table(:contributions)

    drop_if_exists unique_index(:contributors, [:slug], name: "contributors_unique_slug_index")

    drop table(:contributors)

    drop_if_exists unique_index(:cover_assets, [:source_url],
                     name: "cover_assets_unique_source_url_index"
                   )

    alter table(:cover_assets) do
      remove :takedown_state
      remove :cache_policy
      remove :attribution_url
      remove :attribution_text
      remove :rights_basis
      remove :provider
      remove :source_url
    end

    drop constraint(:cover_assignments, "cover_assignments_cover_asset_id_fkey")

    drop constraint(:cover_assignments, "cover_assignments_edition_id_fkey")

    alter table(:cover_assignments) do
      modify :edition_id, :uuid
      modify :cover_asset_id, :uuid
    end

    drop table(:cover_assets)

    drop_if_exists unique_index(:cover_assignments, [:edition_id, :cover_asset_id],
                     name: "cover_assignments_unique_edition_cover_index"
                   )

    drop table(:cover_assignments)

    drop constraint(:curation_overrides, "curation_overrides_source_record_id_fkey")

    drop constraint(:curation_overrides, "curation_overrides_reviewer_id_fkey")

    drop_if_exists unique_index(:curation_overrides, [:entity_type, :entity_id, :field_name],
                     name: "curation_overrides_unique_entity_field_index"
                   )

    drop table(:curation_overrides)

    drop constraint(:editions, "editions_work_id_fkey")

    drop constraint(:editions, "editions_publisher_id_fkey")

    drop constraint(:editions, "editions_imprint_id_fkey")

    drop_if_exists unique_index(:editions, [:slug], name: "editions_unique_slug_index")

    alter table(:editions) do
      remove :imprint_id
      remove :publisher_id
      remove :work_id
      remove :published_on
      remove :format
      remove :slug
      remove :subtitle
      remove :title
    end

    drop constraint(:identifiers, "identifiers_edition_id_fkey")

    alter table(:identifiers) do
      modify :edition_id, :uuid
    end

    drop table(:editions)

    drop_if_exists unique_index(:identifiers, [:identifier_type, :value],
                     name: "identifiers_unique_identifier_index"
                   )

    drop table(:identifiers)

    drop constraint(:import_mappings, "import_mappings_import_run_id_fkey")

    drop_if_exists unique_index(:import_mappings, [:import_run_id, :source_column, :target_field],
                     name: "import_mappings_unique_import_mapping_index"
                   )

    drop table(:import_mappings)

    drop constraint(:review_items, "review_items_import_run_id_fkey")

    drop constraint(:review_items, "review_items_staged_import_row_id_fkey")

    alter table(:review_items) do
      modify :staged_import_row_id, :uuid
      modify :import_run_id, :uuid
    end

    drop constraint(:staged_import_rows, "staged_import_rows_import_run_id_fkey")

    alter table(:staged_import_rows) do
      modify :import_run_id, :uuid
    end

    drop_if_exists unique_index(:import_runs, [:provider, :status, :id],
                     name: "import_runs_unique_provider_status_index"
                   )

    drop table(:import_runs)

    drop constraint(:imprints, "imprints_publisher_id_fkey")

    drop_if_exists unique_index(:imprints, [:publisher_id, :slug],
                     name: "imprints_unique_publisher_slug_index"
                   )

    drop table(:imprints)

    drop_if_exists unique_index(:publishers, [:slug], name: "publishers_unique_slug_index")

    alter table(:publishers) do
      remove :description
      remove :slug
      remove :name
    end

    drop constraint(:series, "series_publisher_id_fkey")

    alter table(:series) do
      modify :publisher_id, :uuid
    end

    drop table(:publishers)

    drop_if_exists unique_index(:review_items, [:import_run_id, :entity_type, :id],
                     name: "review_items_unique_review_item_index"
                   )

    drop table(:review_items)

    drop_if_exists unique_index(:series, [:slug], name: "series_unique_slug_index")

    alter table(:series) do
      remove :publisher_id
      remove :slug
      remove :title
    end

    drop constraint(:series_memberships, "series_memberships_series_id_fkey")

    drop constraint(:series_memberships, "series_memberships_work_id_fkey")

    alter table(:series_memberships) do
      modify :work_id, :uuid
      modify :series_id, :uuid
    end

    drop table(:series)

    drop_if_exists unique_index(:series_memberships, [:series_id, :work_id],
                     name: "series_memberships_unique_series_work_index"
                   )

    drop table(:series_memberships)

    drop constraint(:source_ledger_entries, "source_ledger_entries_source_record_id_fkey")

    drop_if_exists unique_index(
                     :source_ledger_entries,
                     [:source_record_id, :event_type, :occurred_at],
                     name: "source_ledger_entries_unique_source_event_index"
                   )

    drop table(:source_ledger_entries)

    drop_if_exists unique_index(
                     :source_records,
                     [:provider, :source_type, :source_uri, :file_checksum],
                     name: "source_records_unique_source_record_index"
                   )

    drop table(:source_records)

    drop_if_exists unique_index(:staged_import_rows, [:import_run_id, :row_number],
                     name: "staged_import_rows_unique_import_row_index"
                   )

    drop table(:staged_import_rows)

    drop constraint(:tokens, "tokens_user_id_fkey")

    drop_if_exists unique_index(:tokens, [:token_hash], name: "tokens_unique_token_hash_index")

    drop table(:tokens)

    drop_if_exists unique_index(:users, [:email], name: "users_unique_email_index")

    drop table(:users)

    drop_if_exists unique_index(:works, [:slug], name: "works_unique_slug_index")

    drop table(:works)
  end
end
