defmodule Hiraeth.Repo.Migrations.AddSourceBackedBibliographicFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:works) do
      add :original_title, :text
      add :original_language_code, :text
      add :subjects, {:array, :text}, null: false, default: []
    end

    alter table(:editions) do
      add :language_code, :text
      add :page_count, :bigint
      add :height_mm, :bigint
      add :width_mm, :bigint
      add :depth_mm, :bigint
    end
  end

  def down do
    alter table(:editions) do
      remove :depth_mm
      remove :width_mm
      remove :height_mm
      remove :page_count
      remove :language_code
    end

    alter table(:works) do
      remove :subjects
      remove :original_language_code
      remove :original_title
    end
  end
end
