defmodule Hiraeth.Repo.Migrations.AddPublicCatalogIndexes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:source_records, [:provider, :source_type],
             name: "source_records_public_catalog_provider_type_index"
           )

    create index(:source_records, [:source_uri],
             name: "source_records_public_catalog_source_uri_index"
           )

    create index(:series_memberships, [:series_id],
             name: "series_memberships_public_catalog_series_id_index"
           )

    create index(:series_memberships, [:work_id],
             name: "series_memberships_public_catalog_work_id_index"
           )

    create index(:identifiers, [:value], name: "identifiers_public_catalog_value_index")

    create index(:identifiers, [:edition_id], name: "identifiers_public_catalog_edition_id_index")

    create index(:editions, [:imprint_id], name: "editions_public_catalog_imprint_id_index")

    create index(:editions, [:publisher_id], name: "editions_public_catalog_publisher_id_index")

    create index(:editions, [:work_id], name: "editions_public_catalog_work_id_index")

    create index(:cover_assignments, [:cover_asset_id],
             name: "cover_assignments_public_catalog_cover_asset_id_index"
           )

    create index(:cover_assignments, [:edition_id],
             name: "cover_assignments_public_catalog_edition_id_index"
           )

    create index(:contributions, [:contributor_id],
             name: "contributions_public_catalog_contributor_id_index"
           )

    create index(:contributions, [:edition_id],
             name: "contributions_public_catalog_edition_id_index"
           )

    create index(:contributions, [:work_id], name: "contributions_public_catalog_work_id_index")
  end

  def down do
    drop_if_exists index(:contributions, [:work_id],
                     name: "contributions_public_catalog_work_id_index"
                   )

    drop_if_exists index(:contributions, [:edition_id],
                     name: "contributions_public_catalog_edition_id_index"
                   )

    drop_if_exists index(:contributions, [:contributor_id],
                     name: "contributions_public_catalog_contributor_id_index"
                   )

    drop_if_exists index(:cover_assignments, [:edition_id],
                     name: "cover_assignments_public_catalog_edition_id_index"
                   )

    drop_if_exists index(:cover_assignments, [:cover_asset_id],
                     name: "cover_assignments_public_catalog_cover_asset_id_index"
                   )

    drop_if_exists index(:editions, [:work_id], name: "editions_public_catalog_work_id_index")

    drop_if_exists index(:editions, [:publisher_id],
                     name: "editions_public_catalog_publisher_id_index"
                   )

    drop_if_exists index(:editions, [:imprint_id],
                     name: "editions_public_catalog_imprint_id_index"
                   )

    drop_if_exists index(:identifiers, [:edition_id],
                     name: "identifiers_public_catalog_edition_id_index"
                   )

    drop_if_exists index(:identifiers, [:value], name: "identifiers_public_catalog_value_index")

    drop_if_exists index(:series_memberships, [:work_id],
                     name: "series_memberships_public_catalog_work_id_index"
                   )

    drop_if_exists index(:series_memberships, [:series_id],
                     name: "series_memberships_public_catalog_series_id_index"
                   )

    drop_if_exists index(:source_records, [:source_uri],
                     name: "source_records_public_catalog_source_uri_index"
                   )

    drop_if_exists index(:source_records, [:provider, :source_type],
                     name: "source_records_public_catalog_provider_type_index"
                   )
  end
end
