defmodule Hiraeth.Repo.Migrations.T6PublicProseMetadata do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:works) do
      add :description, :text
      add :storefront_url, :text
      add :editorial_praise, {:array, :map}, null: false, default: []
    end
  end

  def down do
    alter table(:works) do
      remove :editorial_praise
      remove :storefront_url
      remove :description
    end
  end
end
