defmodule Hiraeth.Repo.Migrations.SourcesProvenance do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:source_records) do
      modify :imported_at, :utc_datetime, null: false
      modify :raw_payload, :map, null: false
      modify :license_note, :text, null: false
    end

    alter table(:source_ledger_entries) do
      modify :occurred_at, :utc_datetime, null: false
    end

    alter table(:curation_overrides) do
      modify :reviewer_id, :uuid, null: false
      modify :source_record_id, :uuid, null: false
      modify :reason, :text, null: false
      modify :curated_value, :text, null: false
    end
  end

  def down do
    alter table(:curation_overrides) do
      modify :curated_value, :text, null: true
      modify :reason, :text, null: true
      modify :source_record_id, :uuid, null: true
      modify :reviewer_id, :uuid, null: true
    end

    alter table(:source_ledger_entries) do
      modify :occurred_at, :utc_datetime, null: true
    end

    alter table(:source_records) do
      modify :license_note, :text, null: true
      modify :raw_payload, :map, null: true
      modify :imported_at, :utc_datetime, null: true
    end
  end
end
