defmodule Hiraeth.Repo.Migrations.AddAdminAuth do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint("tokens", "tokens_pkey")

    alter table(:users) do
      add :hashed_password, :text, null: false
    end

    alter table(:tokens) do
      remove :user_id
      remove :token_hash
      remove :id
      modify :expires_at, :utc_datetime, null: false

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :extra_data, :map
      add :subject, :text, null: false
      add :jti, :text, null: false, primary_key: true
    end

    drop_if_exists unique_index(:tokens, [:token_hash], name: "tokens_unique_token_hash_index")
  end

  def down do
    drop constraint("tokens", "tokens_pkey")

    create unique_index(:tokens, [:token_hash], name: "tokens_unique_token_hash_index")

    alter table(:tokens) do
      remove :jti
      remove :subject
      remove :extra_data
      remove :created_at
      remove :updated_at
      modify :expires_at, :utc_datetime, null: true
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :token_hash, :text, null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "tokens_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    alter table(:users) do
      remove :hashed_password
    end
  end
end
