defmodule Hiraeth.Repo.Migrations.AddCoverThumbnailFilePath do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:cover_assets) do
      add :thumbnail_file_path, :text
    end
  end

  def down do
    alter table(:cover_assets) do
      remove :thumbnail_file_path
    end
  end
end
