defmodule Hiraeth.Repo.Migrations.SourceRecordImportRunLineage do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:source_records) do
      add :import_run_id,
          references(:import_runs,
            column: :id,
            name: "source_records_import_run_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:source_records, "source_records_import_run_id_fkey")

    alter table(:source_records) do
      remove :import_run_id
    end
  end
end
